[package]
name = "sephirods/wowoptimizer"
version = "0.1.0"
description = "WoW Multi-Class Stat & Gear Optimizer"
license = "MIT"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "."
